development:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: TabClear_development
  pool:     5
  username: Misigno 
  password:
  template: template0

test:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: TabClear_test
  pool:     5
  username: Misigno
  password:
  template: template0

production:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: TabClear_production
  pool:     5
  username: Misigno 
  password:
  template: template0
